-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "filled_quantity" SET DEFAULT 0,
ALTER COLUMN "filled_quantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Position" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Trade" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "total_deposit" SET DEFAULT 0,
ALTER COLUMN "total_deposit" SET DATA TYPE DOUBLE PRECISION;
